# Site
name: "POLY_"
title: "POLY_"
description: "Investigating the “many”" #of culture, music and science
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: 'shelvasha@icloud.com'

# Authors
authors:
  sal:
    name: POLYWRITE
    display_name: POLYWRITE
    avatar: 'assets/images/avatar-write.png'
    email: 'polywrite@icloud.com'
    web: 'https://many.link/polywrite'
    twitter: https://twitter.com/polywrite
    description: "Devoted to writing on “why” of things. Topics: culture and science."
  john:
    name: POLYAUX
    display_name: POLYAUX
    avatar: 'assets/images/avatar-aux.png'
    email: 'polyaux@icloud.com'
    web: 'https://linktr.ee/polyaux'
    twitter: https://twitter.com/polyaux
    description: "Devoted to investigating the diversity of music. Topics: music. Motion graphic designer & music curator."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
